import { expect, test } from '@playwright/test'
import { applyD1, generatePlans, loadDemo, previewF3 } from './helpers'

test('T16/T21/T22 hero flow uses real server snapshots and ranks recovery', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await loadDemo(page)
  await expect(page.locator('.journey-map')).toBeVisible()
  await page.getByRole('button', { name: /Train T1 to Madgaon/i }).click()
  await applyD1(page)
  await expect(page.getByText(/reach the wedding at 8:50 PM IST/i)).toBeVisible()
  await expect(page.getByText(/95 minutes late/i)).toBeVisible()
  await expect(page.getByText(/Hotel check-in is still valid/i)).toBeVisible()
  await expect(page).toHaveScreenshot('baseline-impact.png', { animations: 'disabled', fullPage: true })
  await generatePlans(page)
  await expect(page.locator('.plan-card').nth(0).getByRole('heading')).toHaveText('Fly F3 to Goa')
  await expect(page.locator('.plan-card').nth(1).getByRole('heading')).toHaveText('Fly F2 to Goa')
  await page.getByRole('button', { name: 'Earliest arrival' }).click()
  await expect(page.locator('.plan-card').nth(0).getByRole('heading')).toHaveText('Fly F2 to Goa')
  await expect(page.locator('.rejected')).toContainText(/Fly F4 to Goa/)
  await page.locator('.rejected summary').click()
  await expect(page.locator('.rejected')).toContainText(/50 minutes late/)
  await expect(page).toHaveScreenshot('recovery-comparison.png', { animations: 'disabled', fullPage: true })
  await page.getByRole('button', { name: 'Lowest cost' }).click()
  await previewF3(page)
  await page.getByRole('button', { name: 'Use this plan' }).click()
  await expect(page.getByRole('dialog', { name: /Use this as your new plan/i })).toBeVisible()
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Use simulated plan' }).click()
  await expect(page.getByRole('heading', { name: 'New proposed journey saved' })).toBeVisible()
  await expect(page.getByText(/No external booking was changed/i)).toBeVisible()
  await page.getByRole('button', { name: 'Reset scenario' }).click()
  await expect(page.getByRole('heading', { name: /Your journey is on track/i })).toBeVisible()
})

test('baseline workspace screenshot is stable', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await loadDemo(page)
  await expect(page).toHaveScreenshot('baseline-workspace.png', { animations: 'disabled', fullPage: true })
})
