/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["health_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["health_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Trip */
        post: operations["create_trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/adoptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adopt Plan */
        post: operations["adopt_plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace Constraints Route */
        put: operations["replace_constraints"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/current-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace Current State Route */
        put: operations["replace_current_state"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Event Route */
        post: operations["apply_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/itinerary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace Itinerary */
        put: operations["replace_active_itinerary"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Plans */
        post: operations["generate_plans"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Trip */
        post: operations["reset_trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessibilityState
         * @enum {string}
         */
        AccessibilityState: "suitable" | "unsuitable" | "unknown";
        /** ActivityDefinition */
        ActivityDefinition: {
            /** Booking Id */
            booking_id: string | null;
            /** Derived From Service Id */
            derived_from_service_id?: string | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Earliest Start */
            earliest_start?: string | null;
            /** Hard */
            hard: boolean;
            /** Id */
            id: string;
            kind: components["schemas"]["ActivityKind"];
            /** Latest Start */
            latest_start?: string | null;
            /** Location Id */
            location_id?: string | null;
            /** Provenance Id */
            provenance_id: string | null;
            /** Readiness Allowance Sec */
            readiness_allowance_sec?: number | null;
            /** Service Id */
            service_id?: string | null;
            /** Start At */
            start_at?: string | null;
            /** Transfer Template Id */
            transfer_template_id?: string | null;
        };
        /**
         * ActivityKind
         * @enum {string}
         */
        ActivityKind: "fixed_transport" | "flexible_transfer" | "processing" | "hotel_checkin" | "commitment";
        /** AdoptionCommand */
        AdoptionCommand: {
            /**
             * Acknowledge Simulation
             * @constant
             */
            acknowledge_simulation: true;
            /** Expected Trip Version */
            expected_trip_version: number;
            /** Plan Id */
            plan_id: string;
        };
        /** AdoptionRecord */
        AdoptionRecord: {
            /**
             * Acknowledge Simulation
             * @constant
             */
            acknowledge_simulation: true;
            /**
             * Adopted At
             * Format: date-time
             */
            adopted_at: string;
            /** Catalog Version */
            catalog_version: string;
            /**
             * External Booking Executed
             * @constant
             */
            external_booking_executed: false;
            /** Id */
            id: string;
            /** Plan Id */
            plan_id: string;
            /** Prior Trip Version */
            prior_trip_version: number;
            /** Resulting Trip Version */
            resulting_trip_version: number;
            /** Trip Id */
            trip_id: string;
        };
        /** AdoptionResponse */
        AdoptionResponse: {
            adoption: components["schemas"]["AdoptionRecord"];
            /** Provider Actions */
            provider_actions: components["schemas"]["ProviderAction"][];
            snapshot: components["schemas"]["TripViewSnapshot"];
        };
        /**
         * ApiErrorCode
         * @enum {string}
         */
        ApiErrorCode: "INVALID_JSON" | "INVALID_REQUEST" | "VALIDATION_ERROR" | "UNKNOWN_FIELD" | "MISSING_FIELD" | "INVALID_DISCRIMINATOR" | "INVALID_TIMEZONE" | "INVALID_MONEY" | "DUPLICATE_ID" | "REFERENCE_NOT_FOUND" | "INVALID_DEPENDENCY_GRAPH" | "INVALID_CURRENT_STATE" | "BASELINE_RECONCILIATION_FAILED" | "TRIP_NOT_FOUND" | "SCENARIO_NOT_FOUND" | "PLAN_NOT_FOUND" | "CATALOG_VERSION_CONFLICT" | "PROVENANCE_ID_CONFLICT" | "PLAN_EXPIRED" | "PLAN_NOT_ADOPTABLE" | "RESET_NOT_SUPPORTED" | "SIMULATION_ACKNOWLEDGEMENT_REQUIRED" | "REQUEST_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "INTERNAL_DATA_INTEGRITY_ERROR" | "INTERNAL_ERROR" | "SERVICE_UNAVAILABLE" | "EVENT_ID_CONFLICT" | "EVENT_SEQUENCE_STALE" | "VERSION_CONFLICT" | "STALE_PLAN" | "COMPLETED_ACTIVITY_IMMUTABLE" | "ACTIVE_ACTIVITY_IMMUTABLE" | "HARD_CHANGE_ACKNOWLEDGEMENT_REQUIRED" | "ITINERARY_EDIT_INVALID";
        /** AvailableActions */
        AvailableActions: {
            /** Can Adopt Plan */
            can_adopt_plan: boolean;
            /** Can Apply Event */
            can_apply_event: boolean;
            /** Can Edit Constraints */
            can_edit_constraints: boolean;
            /** Can Edit Current State */
            can_edit_current_state: boolean;
            /** Can Edit Itinerary */
            can_edit_itinerary: boolean;
            /** Can Generate Plans */
            can_generate_plans: boolean;
            /** Can Reset */
            can_reset: boolean;
        };
        /** Booking */
        Booking: {
            /** Id */
            id: string;
            /** Paid Paise */
            paid_paise: number;
            /** Policy Id */
            policy_id: string;
            /** Provenance Id */
            provenance_id: string;
            /** Remaining Paise */
            remaining_paise: number;
            /** Service Or Activity Ids */
            service_or_activity_ids: string[];
            state: components["schemas"]["BookingState"];
        };
        /**
         * BookingState
         * @enum {string}
         */
        BookingState: "fictional" | "user_reported" | "provider_confirmed" | "cancelled";
        /** BooleanEvidenceValue */
        BooleanEvidenceValue: {
            /** Unit */
            unit: string | null;
            /** Value */
            value: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            value_kind: "boolean";
        };
        /** ConstraintCheck */
        ConstraintCheck: {
            /** Constraint Id */
            constraint_id: string;
            observed: components["schemas"]["EvidenceValue"];
            /** Passed */
            passed: boolean | null;
            /** Provenance Ids */
            provenance_ids: string[];
            reason_code: components["schemas"]["DomainReasonCode"];
            required: components["schemas"]["EvidenceValue"];
        };
        /** Constraints */
        Constraints: {
            /** Accessibility Required */
            accessibility_required: boolean;
            /** Allowed Modes */
            allowed_modes: components["schemas"]["TransportMode"][];
            /**
             * Horizon End
             * Format: date-time
             */
            horizon_end: string;
            /** Max Cash Required Paise */
            max_cash_required_paise: number;
            /** Max Incremental Cost Paise */
            max_incremental_cost_paise: number;
            /** Max New Fixed Legs */
            max_new_fixed_legs: number;
            /** Max Transfer Legs */
            max_transfer_legs: number;
            /**
             * Party Size
             * @constant
             */
            party_size: 1;
            ranking_preset: components["schemas"]["RankingPreset"];
            /** Required Commitment Ids */
            required_commitment_ids: string[];
            /** Risk Threshold Sec */
            risk_threshold_sec: number;
        };
        /** ConstraintsReplaceCommand */
        ConstraintsReplaceCommand: {
            constraints: components["schemas"]["Constraints"];
            /** Expected Trip Version */
            expected_trip_version: number;
            provenance: components["schemas"]["ProvenanceRecord"];
        };
        /** CurrentState */
        CurrentState: {
            /** Active Service Id */
            active_service_id: string | null;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Completed Activity Ids */
            completed_activity_ids: string[];
            /** Location Id */
            location_id: string | null;
            /** Next Recovery Point Id */
            next_recovery_point_id: string | null;
            phase: components["schemas"]["TravelerPhase"];
            /** Provenance Id */
            provenance_id: string;
        };
        /** CurrentStateReplaceCommand */
        CurrentStateReplaceCommand: {
            current_state: components["schemas"]["CurrentState"];
            /** Expected Trip Version */
            expected_trip_version: number;
            provenance: components["schemas"]["ProvenanceRecord"];
        };
        /** Dependency */
        Dependency: {
            /** Buffer Sec */
            buffer_sec: number;
            /** From Id */
            from_id: string;
            /** Id */
            id: string;
            /** Reason */
            reason: string;
            /** To Id */
            to_id: string;
        };
        /**
         * DomainReasonCode
         * @enum {string}
         */
        DomainReasonCode: "HARD_DEADLINE_MISSED" | "LOW_POSITIVE_SLACK" | "SERVICE_CANCELLED" | "SERVICE_CUTOFF_MISSED" | "LOCATION_UNREACHABLE" | "CAPACITY_INSUFFICIENT" | "CAPACITY_UNKNOWN" | "ACTIVITY_WINDOW_MISSED" | "ACCESSIBILITY_UNSUITABLE" | "ACCESSIBILITY_UNKNOWN" | "CASH_LIMIT_EXCEEDED" | "EXTRA_COST_LIMIT_EXCEEDED" | "MODE_NOT_ALLOWED" | "SEARCH_HORIZON_EXCEEDED" | "MAX_FIXED_LEGS_EXCEEDED" | "MAX_TRANSFER_LEGS_EXCEEDED" | "REQUIRED_FACT_MISSING" | "UNSUPPORTED_CURRENT_STATE" | "STALE_PLAN" | "SEARCH_INCOMPLETE" | "INVALID_DEPENDENCY_GRAPH" | "DUPLICATE_EVENT" | "EVENT_ID_CONFLICT" | "EVENT_SEQUENCE_STALE" | "VERSION_CONFLICT" | "POLICY_CONFIRMATION_REQUIRED" | "HARD_CONSTRAINTS_PASS";
        /** DurationEvidenceValue */
        DurationEvidenceValue: {
            /** Unit */
            unit: string | null;
            /** Value */
            value: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            value_kind: "duration_sec";
        };
        /** EffectiveServiceState */
        EffectiveServiceState: {
            /**
             * Effective Arrival
             * Format: date-time
             */
            effective_arrival: string;
            /**
             * Effective Departure
             * Format: date-time
             */
            effective_departure: string;
            /** Last Event Id */
            last_event_id: string | null;
            /** Provenance Id */
            provenance_id: string;
            /** Service Id */
            service_id: string;
            status: components["schemas"]["ServiceStatus"];
        };
        /** EntityIdEvidenceValue */
        EntityIdEvidenceValue: {
            /** Unit */
            unit: string | null;
            /** Value */
            value: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            value_kind: "entity_id";
        };
        /** EvaluatedActivity */
        EvaluatedActivity: {
            /** Activity Id */
            activity_id: string;
            /** Cutoff At */
            cutoff_at: string | null;
            /** Destination Id */
            destination_id: string | null;
            /** End At */
            end_at: string | null;
            kind: components["schemas"]["ActivityKind"];
            /** Origin Id */
            origin_id: string | null;
            /** Provenance Ids */
            provenance_ids: string[];
            /** Ready At */
            ready_at: string | null;
            /** Reason Codes */
            reason_codes: components["schemas"]["DomainReasonCode"][];
            /** Service Id */
            service_id: string | null;
            /** Slack Sec */
            slack_sec: number | null;
            /** Start At */
            start_at: string | null;
            status: components["schemas"]["FeasibilityStatus"];
            /** Transfer Template Id */
            transfer_template_id: string | null;
        };
        /** EventResponse */
        EventResponse: {
            event_result: components["schemas"]["EventResult"];
        };
        /** EventResult */
        EventResult: {
            /** Applied */
            applied: boolean;
            /** Current Trip Version */
            current_trip_version: number;
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "applied" | "duplicate";
            /** Event Id */
            event_id: string;
            /** Prior Trip Version */
            prior_trip_version: number;
            snapshot: components["schemas"]["TripViewSnapshot"];
        };
        EvidenceValue: components["schemas"]["UnknownEvidenceValue"] | components["schemas"]["TimestampEvidenceValue"] | components["schemas"]["DurationEvidenceValue"] | components["schemas"]["MoneyEvidenceValue"] | components["schemas"]["IntegerEvidenceValue"] | components["schemas"]["BooleanEvidenceValue"] | components["schemas"]["TextEvidenceValue"] | components["schemas"]["EntityIdEvidenceValue"] | components["schemas"]["StringListEvidenceValue"];
        /**
         * FeasibilityStatus
         * @enum {string}
         */
        FeasibilityStatus: "feasible" | "at_risk" | "infeasible" | "blocked" | "unknown";
        /**
         * FixedServiceMode
         * @enum {string}
         */
        FixedServiceMode: "rail" | "air" | "bus";
        /** FixtureTripCreate */
        FixtureTripCreate: {
            /** Display Name */
            display_name: string | null;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Source Type
             * @constant
             */
            source_type: "fixture";
        };
        /** ImpactRecord */
        ImpactRecord: {
            /** Activity Id */
            activity_id: string;
            /** After Ready At */
            after_ready_at: string | null;
            /** After Slack Sec */
            after_slack_sec: number | null;
            after_status: components["schemas"]["FeasibilityStatus"];
            /** Before Ready At */
            before_ready_at: string | null;
            /** Before Slack Sec */
            before_slack_sec: number | null;
            before_status: components["schemas"]["FeasibilityStatus"];
            /** Causal Activity Path */
            causal_activity_path: string[];
            /** Constraint Checks */
            constraint_checks: components["schemas"]["ConstraintCheck"][];
            /** Cutoff At */
            cutoff_at: string | null;
            /** Reason Codes */
            reason_codes: components["schemas"]["DomainReasonCode"][];
            /** Root Event Ids */
            root_event_ids: string[];
        };
        /** IntegerEvidenceValue */
        IntegerEvidenceValue: {
            /** Unit */
            unit: string | null;
            /** Value */
            value: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            value_kind: "integer";
        };
        /** ItineraryDefinition */
        "ItineraryDefinition-Input": {
            /** Activities */
            activities: components["schemas"]["ActivityDefinition"][];
            /** Dependencies */
            dependencies: components["schemas"]["Dependency"][];
        };
        /** ItineraryDefinition */
        "ItineraryDefinition-Output": {
            /** Activities */
            activities: components["schemas"]["ActivityDefinition"][];
            /** Dependencies */
            dependencies: components["schemas"]["Dependency"][];
        };
        /** ItineraryEditCommand */
        ItineraryEditCommand: {
            /** Acknowledge Hard Changes */
            acknowledge_hard_changes: boolean;
            active_itinerary: components["schemas"]["ItineraryDefinition-Input"];
            constraints: components["schemas"]["Constraints"];
            /** Expected Trip Version */
            expected_trip_version: number;
            provenance: components["schemas"]["ProvenanceRecord"];
        };
        /** LiveHealthResponse */
        LiveHealthResponse: {
            /**
             * Contract Version
             * @default resilitrip-api-1.0
             * @constant
             */
            contract_version: "resilitrip-api-1.0";
            /**
             * Service
             * @default resilitrip
             * @constant
             */
            service: "resilitrip";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** Location */
        Location: {
            /** Code */
            code: string | null;
            /**
             * Field Provenance
             * @default []
             */
            field_provenance: unknown[];
            /** Id */
            id: string;
            kind: components["schemas"]["LocationKind"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Provenance Id */
            provenance_id: string;
            /** Terminal */
            terminal: string | null;
        };
        /**
         * LocationKind
         * @enum {string}
         */
        LocationKind: "rail_station" | "airport_terminal" | "hotel" | "venue" | "generic_point";
        /** ManualTripCreate */
        ManualTripCreate: {
            /** Baseline Money Items */
            baseline_money_items: components["schemas"]["MoneyItem"][];
            /** Bookings */
            bookings: components["schemas"]["Booking"][];
            catalog: components["schemas"]["ServiceCatalog-Input"];
            constraints: components["schemas"]["Constraints"];
            /** Constraints Provenance Id */
            constraints_provenance_id: string;
            current_state: components["schemas"]["CurrentState"];
            /** Decision Allowance Sec */
            decision_allowance_sec: number;
            /**
             * Display Timezone
             * @constant
             */
            display_timezone: "Asia/Kolkata";
            original_itinerary: components["schemas"]["ItineraryDefinition-Input"];
            /**
             * Source Type
             * @constant
             */
            source_type: "manual";
            traveler: components["schemas"]["TravelerProfile"];
            /** Trip Provenance */
            trip_provenance: components["schemas"]["ProvenanceRecord"][];
        };
        /**
         * MoneyCategory
         * @enum {string}
         */
        MoneyCategory: "retained_charge" | "new_purchase" | "mandatory_fee" | "potential_refund" | "received_refund" | "sunk_cost";
        /** MoneyEvidenceValue */
        MoneyEvidenceValue: {
            /** Unit */
            unit: string | null;
            /** Value */
            value: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            value_kind: "money_paise";
        };
        /** MoneyItem */
        MoneyItem: {
            /** Amount Paise */
            amount_paise: number | null;
            /** Booking Id */
            booking_id: string | null;
            category: components["schemas"]["MoneyCategory"];
            /** Id */
            id: string;
            payment_state: components["schemas"]["PaymentState"];
            /** Provenance Id */
            provenance_id: string;
            /** Service Id */
            service_id: string | null;
            /** Transfer Template Id */
            transfer_template_id: string | null;
        };
        /** MutationResponse */
        MutationResponse: {
            /** Changed */
            changed: boolean;
            /** Current Trip Version */
            current_trip_version: number;
            /**
             * Mutation Kind
             * @enum {string}
             */
            mutation_kind: "created" | "event" | "constraints" | "current_state" | "itinerary_edit" | "adoption" | "reset";
            /** Prior Trip Version */
            prior_trip_version: number;
            snapshot: components["schemas"]["TripViewSnapshot"];
            /** Staled Plan Count */
            staled_plan_count: number;
        };
        /**
         * PaymentState
         * @enum {string}
         */
        PaymentState: "paid" | "due" | "potential";
        /** PlanEvaluation */
        PlanEvaluation: {
            /** Activity Sequence */
            activity_sequence: components["schemas"]["EvaluatedActivity"][];
            /**
             * Bookable
             * @constant
             */
            bookable: false;
            /** Cash Required Paise */
            cash_required_paise: number;
            /** Catalog Version */
            catalog_version: string;
            /** Changed Original Booking Ids */
            changed_original_booking_ids: string[];
            /** Constraint Checks */
            constraint_checks: components["schemas"]["ConstraintCheck"][];
            /** Display Rank */
            display_rank: number | null;
            evaluation_status: components["schemas"]["FeasibilityStatus"];
            /** Event Slack Sec */
            event_slack_sec: number;
            /**
             * Final Required Arrival At
             * Format: date-time
             */
            final_required_arrival_at: string;
            /** Frontier Member */
            frontier_member: boolean;
            /** Id */
            id: string;
            /** Incremental Cost Paise */
            incremental_cost_paise: number;
            lifecycle_status: components["schemas"]["PlanLifecycleStatus"];
            /** Money Items */
            money_items: components["schemas"]["MoneyItem"][];
            objective_values: components["schemas"]["PlanObjectiveValues"];
            /** Potential Refund Paise */
            potential_refund_paise: number | null;
            proposed_itinerary: components["schemas"]["ItineraryDefinition-Output"];
            /** Provenance Ids */
            provenance_ids: string[];
            ranking_reason_code: components["schemas"]["RankingReasonCode"] | null;
            /** Reason Codes */
            reason_codes: components["schemas"]["DomainReasonCode"][];
            /** Run Id */
            run_id: string | null;
            /** Sequence Ids */
            sequence_ids: string[];
            /** Sequence Signature */
            sequence_signature: string;
            /** Service Ids */
            service_ids: string[];
            /**
             * Simulated
             * @constant
             */
            simulated: true;
            /** Transfer Template Ids */
            transfer_template_ids: string[];
            /** Trip Id */
            trip_id: string;
            /** Trip Version */
            trip_version: number;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
        };
        /**
         * PlanLifecycleStatus
         * @enum {string}
         */
        PlanLifecycleStatus: "preview" | "adopted" | "stale";
        /** PlanObjectiveValues */
        PlanObjectiveValues: {
            /** Cash Required Paise */
            cash_required_paise: number;
            /** Changed Original Booking Count */
            changed_original_booking_count: number;
            /**
             * Final Required Arrival At
             * Format: date-time
             */
            final_required_arrival_at: string;
        };
        /** PlannerCommand */
        PlannerCommand: {
            /** Expected Catalog Version */
            expected_catalog_version: string;
            /** Expected Trip Version */
            expected_trip_version: number;
            ranking_preset: components["schemas"]["RankingPreset"];
        };
        /** PlannerCounts */
        PlannerCounts: {
            /** Complete Paths */
            complete_paths: number;
            /** Displayed Total */
            displayed_total: number;
            /** Duplicate Paths */
            duplicate_paths: number;
            /** Feasible Total */
            feasible_total: number;
            /** Frontier Total */
            frontier_total: number;
            /** Pruned By Reason */
            pruned_by_reason: {
                [key: string]: number;
            };
            /** Rejected Total */
            rejected_total: number;
            /** States Expanded */
            states_expanded: number;
            /** Uncertain Total */
            uncertain_total: number;
        };
        /** PlannerResponse */
        PlannerResponse: {
            /** Catalog Version */
            catalog_version: string;
            planner_result: components["schemas"]["PlannerResult"];
            /** Snapshot Version */
            snapshot_version: number;
        };
        /** PlannerResult */
        PlannerResult: {
            /** Catalog Version */
            catalog_version: string;
            counts: components["schemas"]["PlannerCounts"];
            /** Feasible Plans */
            feasible_plans: components["schemas"]["PlanEvaluation"][];
            interruption_reason: components["schemas"]["DomainReasonCode"] | null;
            ranking_preset: components["schemas"]["RankingPreset"];
            /** Rejected Plans */
            rejected_plans: components["schemas"]["PlanEvaluation"][];
            result_status: components["schemas"]["PlannerResultStatus"];
            /** Run Id */
            run_id: string;
            /** Runtime Ms */
            runtime_ms: number;
            scope: components["schemas"]["SearchScope"];
            /** Search Complete */
            search_complete: boolean;
            /** Trip Id */
            trip_id: string;
            /** Trip Version */
            trip_version: number;
            /** Uncertain Plans */
            uncertain_plans: components["schemas"]["PlanEvaluation"][];
        };
        /**
         * PlannerResultStatus
         * @enum {string}
         */
        PlannerResultStatus: "complete" | "no_feasible_catalog_plan" | "needs_input" | "partial_search" | "error";
        /** PolicyRecord */
        PolicyRecord: {
            /** Abandon Before Pickup Fee Paise */
            abandon_before_pickup_fee_paise?: number | null;
            /** Additional Checkin Fee Paise */
            additional_checkin_fee_paise?: number | null;
            /** Additional Fee Paise */
            additional_fee_paise?: number | null;
            /** Calculation Allowed */
            calculation_allowed: boolean;
            /** Conflict */
            conflict: boolean;
            /**
             * Exclusions
             * @default []
             */
            exclusions: string[];
            /** Id */
            id: string;
            /** Listed Fare Due If Selected */
            listed_fare_due_if_selected?: boolean | null;
            /** Paid Paise */
            paid_paise?: number | null;
            /**
             * Policy Kind
             * @enum {string}
             */
            policy_kind: "flexible_transfer_fictional" | "hotel_retained_fictional" | "new_fixed_service_fictional" | "provider_guidance";
            /** Provenance Id */
            provenance_id: string;
            /**
             * Required Inputs
             * @default []
             */
            required_inputs: string[];
            /** Result */
            result?: "needs_provider_confirmation" | null;
            /** Scope */
            scope: string;
            /** Selected Price Due */
            selected_price_due?: boolean | null;
            /**
             * Source Class
             * @enum {string}
             */
            source_class: "synthetic" | "official_guidance" | "user_reported";
            verification: components["schemas"]["VerificationState"];
        };
        /** ProblemDetail */
        ProblemDetail: {
            code: components["schemas"]["ApiErrorCode"];
            /** Current Catalog Version */
            current_catalog_version?: string | null;
            /** Current Trip Version */
            current_trip_version?: number | null;
            /**
             * Field Errors
             * @default []
             */
            field_errors: components["schemas"]["ProblemFieldError"][];
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ProblemFieldError */
        ProblemFieldError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Path */
            path: string;
            rejected_value?: components["schemas"]["EvidenceValue"] | null;
        };
        /** ProblemResponse */
        ProblemResponse: {
            error: components["schemas"]["ProblemDetail"];
        };
        /**
         * ProvenanceKind
         * @enum {string}
         */
        ProvenanceKind: "synthetic" | "user_reported" | "official_replay" | "authorized_live" | "estimate";
        /** ProvenanceRecord */
        ProvenanceRecord: {
            /** Id */
            id: string;
            kind: components["schemas"]["ProvenanceKind"];
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Source Ref */
            source_ref: string;
            /** Valid Until */
            valid_until: string | null;
            verification: components["schemas"]["VerificationState"];
        };
        /** ProviderAction */
        ProviderAction: {
            /** Handoff Available */
            handoff_available: boolean;
            /** Id */
            id: string;
            /**
             * Provider Key
             * @enum {string}
             */
            provider_key: "indian_rail_enquiry" | "airline_or_ota" | "hotel" | "local_transfer";
            /** Reason */
            reason: string;
            /** Required Before External Change */
            required_before_external_change: boolean;
            /**
             * Status
             * @constant
             */
            status: "not_started";
            /** Title */
            title: string;
        };
        /**
         * RankingPreset
         * @enum {string}
         */
        RankingPreset: "cheapest" | "fastest" | "fewest_changes";
        /**
         * RankingReasonCode
         * @enum {string}
         */
        RankingReasonCode: "LOWEST_CASH_ON_FRONTIER" | "EARLIEST_ARRIVAL_ON_FRONTIER" | "FEWEST_CHANGES_ON_FRONTIER" | "TIE_BROKEN_BY_CASH" | "TIE_BROKEN_BY_ARRIVAL" | "TIE_BROKEN_BY_CHANGES" | "TIE_BROKEN_BY_PLAN_ID";
        /** ReadyHealthResponse */
        ReadyHealthResponse: {
            /**
             * Contract Version
             * @default resilitrip-api-1.0
             * @constant
             */
            contract_version: "resilitrip-api-1.0";
            /**
             * Database
             * @default ok
             * @constant
             */
            database: "ok";
            /** Installed Scenario Count */
            installed_scenario_count: number;
            /** Schema Revision */
            schema_revision: string;
            /**
             * Service
             * @default resilitrip
             * @constant
             */
            service: "resilitrip";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** ResetCommand */
        ResetCommand: {
            /** Expected Trip Version */
            expected_trip_version: number;
            /** Scenario Id */
            scenario_id: string;
        };
        /** ScenarioSummary */
        ScenarioSummary: {
            /** Available */
            available: boolean;
            /** Catalog Version */
            catalog_version: string;
            /**
             * Currency
             * @constant
             */
            currency: "INR";
            /**
             * Display Timezone
             * @constant
             */
            display_timezone: "Asia/Kolkata";
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Truth Label */
            truth_label: string;
        };
        /** SearchScope */
        SearchScope: {
            /** Catalog Version */
            catalog_version: string;
            /**
             * Horizon End
             * Format: date-time
             */
            horizon_end: string;
            /**
             * Max Activities
             * @constant
             */
            max_activities: 20;
            /** Max Catalog Services */
            max_catalog_services: number;
            /** Max New Fixed Legs */
            max_new_fixed_legs: number;
            /** Max Transfer Legs */
            max_transfer_legs: number;
            /**
             * Replay As Of
             * Format: date-time
             */
            replay_as_of: string;
        };
        /** ServiceCancelledEvent */
        ServiceCancelledEvent: {
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /** Event Id */
            event_id: string;
            /** Expected Trip Version */
            expected_trip_version: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            provenance: components["schemas"]["ProvenanceRecord"];
            /** Service Id */
            service_id: string;
            /** Source Id */
            source_id: string;
            /** Source Sequence */
            source_sequence: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SERVICE_CANCELLED";
        };
        /** ServiceCatalog */
        "ServiceCatalog-Input": {
            /** Catalog Version */
            catalog_version: string;
            /**
             * Currency
             * @constant
             */
            currency: "INR";
            /**
             * Display Timezone
             * @constant
             */
            display_timezone: "Asia/Kolkata";
            /** Locations */
            locations: components["schemas"]["Location"][];
            /** Policies */
            policies: components["schemas"]["PolicyRecord"][];
            /** Provenance */
            provenance: components["schemas"]["ProvenanceRecord"][];
            /** Scenario Id */
            scenario_id: string | null;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "resilitrip-api-1.0";
            /** Services */
            services: components["schemas"]["ServiceDefinition"][];
            /** Transfer Templates */
            transfer_templates: components["schemas"]["TransferTemplate"][];
        };
        /** ServiceCatalog */
        "ServiceCatalog-Output": {
            /** Catalog Version */
            catalog_version: string;
            /**
             * Currency
             * @constant
             */
            currency: "INR";
            /**
             * Display Timezone
             * @constant
             */
            display_timezone: "Asia/Kolkata";
            /** Locations */
            locations: components["schemas"]["Location"][];
            /** Policies */
            policies: components["schemas"]["PolicyRecord"][];
            /** Provenance */
            provenance: components["schemas"]["ProvenanceRecord"][];
            /** Scenario Id */
            scenario_id: string | null;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "resilitrip-api-1.0";
            /** Services */
            services: components["schemas"]["ServiceDefinition"][];
            /** Transfer Templates */
            transfer_templates: components["schemas"]["TransferTemplate"][];
        };
        /** ServiceDefinition */
        ServiceDefinition: {
            /** Capacity */
            capacity: number | null;
            /** Destination Id */
            destination_id: string;
            /** Display Code */
            display_code: string;
            /** Exit Allowance Sec */
            exit_allowance_sec: number;
            /**
             * Field Provenance
             * @default []
             */
            field_provenance: unknown[];
            /** Id */
            id: string;
            mode: components["schemas"]["FixedServiceMode"];
            /** Origin Allowance Sec */
            origin_allowance_sec: number;
            /** Origin Id */
            origin_id: string;
            /** Policy Id */
            policy_id: string;
            /** Price Paise */
            price_paise: number | null;
            price_state: components["schemas"]["ServicePriceState"];
            /** Provenance Id */
            provenance_id: string;
            /**
             * Scheduled Arrival
             * Format: date-time
             */
            scheduled_arrival: string;
            /**
             * Scheduled Departure
             * Format: date-time
             */
            scheduled_departure: string;
            /** Service Date */
            service_date: string;
        };
        /**
         * ServicePriceState
         * @enum {string}
         */
        ServicePriceState: "paid" | "due_if_selected";
        /**
         * ServiceStatus
         * @enum {string}
         */
        ServiceStatus: "scheduled" | "delayed" | "cancelled";
        /** StringListEvidenceValue */
        StringListEvidenceValue: {
            /** Unit */
            unit: string | null;
            /** Value */
            value: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            value_kind: "string_list";
        };
        /** TextEvidenceValue */
        TextEvidenceValue: {
            /** Unit */
            unit: string | null;
            /** Value */
            value: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            value_kind: "text";
        };
        /** TimestampEvidenceValue */
        TimestampEvidenceValue: {
            /** Unit */
            unit: string | null;
            /**
             * Value
             * Format: date-time
             */
            value: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            value_kind: "timestamp";
        };
        /** TimingReplayEvent */
        TimingReplayEvent: {
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /** Event Id */
            event_id: string;
            /** Expected Trip Version */
            expected_trip_version: number;
            /**
             * New Arrival At
             * Format: date-time
             */
            new_arrival_at: string;
            /**
             * New Departure At
             * Format: date-time
             */
            new_departure_at: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            provenance: components["schemas"]["ProvenanceRecord"];
            /** Service Id */
            service_id: string;
            /** Source Id */
            source_id: string;
            /** Source Sequence */
            source_sequence: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SERVICE_TIMING_UPDATED";
        };
        /** TransferTemplate */
        TransferTemplate: {
            accessibility: components["schemas"]["AccessibilityState"];
            /** Capacity */
            capacity: number | null;
            /** Destination Id */
            destination_id: string;
            /** Display Code */
            display_code: string;
            /** Duration Sec */
            duration_sec: number;
            /**
             * Field Provenance
             * @default []
             */
            field_provenance: unknown[];
            /** Id */
            id: string;
            /**
             * Latest Start
             * Format: date-time
             */
            latest_start: string;
            /** Origin Id */
            origin_id: string;
            /** Policy Id */
            policy_id: string;
            /** Price Paise */
            price_paise: number | null;
            /** Provenance Id */
            provenance_id: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /**
         * TransportMode
         * @enum {string}
         */
        TransportMode: "rail" | "air" | "bus" | "road_transfer";
        /**
         * TravelerPhase
         * @enum {string}
         */
        TravelerPhase: "not_started" | "at_location" | "onboard" | "completed";
        /** TravelerProfile */
        TravelerProfile: {
            /** Accessibility Required */
            accessibility_required: boolean;
            /** Display Name */
            display_name: string | null;
            /**
             * Party Size
             * @constant
             */
            party_size: 1;
        };
        /** TripAggregate */
        TripAggregate: {
            active_itinerary: components["schemas"]["ItineraryDefinition-Output"];
            /** Adopted Plan Id */
            adopted_plan_id?: string | null;
            /** Baseline Money Items */
            baseline_money_items: components["schemas"]["MoneyItem"][];
            /** Baseline Remaining Spend Paise */
            baseline_remaining_spend_paise: number;
            /** Bookings */
            bookings: components["schemas"]["Booking"][];
            /** Catalog Version */
            catalog_version: string;
            constraints: components["schemas"]["Constraints"];
            /** Constraints Provenance Id */
            constraints_provenance_id: string;
            /**
             * Currency
             * @constant
             */
            currency: "INR";
            current_state: components["schemas"]["CurrentState"];
            /** Decision Allowance Sec */
            decision_allowance_sec: number;
            /**
             * Display Timezone
             * @constant
             */
            display_timezone: "Asia/Kolkata";
            /** Effective Services */
            effective_services: components["schemas"]["EffectiveServiceState"][];
            /** Id */
            id: string;
            /**
             * Last Mutation Kind
             * @default created
             * @enum {string}
             */
            last_mutation_kind: "created" | "event" | "constraints" | "current_state" | "itinerary_edit" | "adoption" | "reset";
            /**
             * Mode
             * @constant
             */
            mode: "demo";
            original_itinerary: components["schemas"]["ItineraryDefinition-Output"];
            /** Provenance */
            provenance: components["schemas"]["ProvenanceRecord"][];
            /** Scenario Id */
            scenario_id: string | null;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "resilitrip-api-1.0";
            traveler: components["schemas"]["TravelerProfile"];
            /** Truth Label */
            truth_label: string;
            /** Version */
            version: number;
        };
        /** TripCreatedResponse */
        TripCreatedResponse: {
            /** Catalog Version */
            catalog_version: string;
            snapshot: components["schemas"]["TripViewSnapshot"];
            /** Trip Id */
            trip_id: string;
            /** Trip Version */
            trip_version: number;
        };
        /** TripSnapshotResponse */
        TripSnapshotResponse: {
            snapshot: components["schemas"]["TripViewSnapshot"];
        };
        /** TripViewSnapshot */
        TripViewSnapshot: {
            available_actions: components["schemas"]["AvailableActions"];
            catalog: components["schemas"]["ServiceCatalog-Output"];
            /** Evaluated Itinerary */
            evaluated_itinerary: components["schemas"]["EvaluatedActivity"][];
            /**
             * Impacts
             * @default []
             */
            impacts: components["schemas"]["ImpactRecord"][];
            overall_status: components["schemas"]["FeasibilityStatus"];
            /** Provenance */
            provenance: components["schemas"]["ProvenanceRecord"][];
            trip: components["schemas"]["TripAggregate"];
        };
        /** UnknownEvidenceValue */
        UnknownEvidenceValue: {
            /** Unit */
            unit: string | null;
            /** Value */
            value: null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            value_kind: "unknown";
        };
        /**
         * VerificationState
         * @enum {string}
         */
        VerificationState: "unverified" | "fixture" | "provider_confirmed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveHealthResponse"];
                };
            };
        };
    };
    health_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyHealthResponse"];
                };
            };
        };
    };
    list_scenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummary"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    create_trip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FixtureTripCreate"] | components["schemas"]["ManualTripCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripCreatedResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    get_trip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSnapshotResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    adopt_plan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdoptionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdoptionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    replace_constraints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConstraintsReplaceCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    replace_current_state: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurrentStateReplaceCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    apply_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimingReplayEvent"] | components["schemas"]["ServiceCancelledEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    replace_active_itinerary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItineraryEditCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    generate_plans: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannerCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    get_plan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanEvaluation"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    reset_trip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
}
